### ISSUE TITLE
RichText.asText prepends newline char to string

### ISSUE THREAD

**Issue by jdwillemse** [prismicio/prismic-reactjs#10]
This is the object that is returned from Prismic:
```JSON
[{"type":"heading1","text":"Velkomin","spans":[]}]
```

This is what `RichText.asText()` outputs:
```JSON
"\n Velkomin"
```
Is this a bug or expected behaviour? I would expect the output to be "Velkomin".

**Comment by arnaudlewis** [comment]
fixed in 0.3.1. Thanks for your report.
