### ISSUE TITLE
richText.render() outputs &nbsp;

### ISSUE THREAD

**Issue by tylermcrobert** [prismicio/prismic-reactjs#12]
I'm using `richText.render()` and it works perfectly, however, it renders out `&nbsp;` as text.

**Comment by hypervillain** [comment]
Hey @tylermcrobert I'm unable to reproduce, could you give me more information?

**Comment by vuquanghoang** [comment]
I also got the same issue. I tried to type text into CMS and then get content by this code: 
`<RichTextContainer>{RichText.render(slice.primary.content)}</RichTextContainer>;`

All of the spaces turned into &nbsp;. Not sure you guys know about it at this moment?

**Comment by hypervillain** [comment]
Hey @vuquanghoang,

do you know which version this happens with? I will try to reproduce on my side. Is there any specific content in your rich text (videos, embeds...)?

**Comment by acd02** [comment]
Hello, I got the same issue here,

prismic-reactjs version: "1.1.1"

Render:
___
![image](https://i.imgur.com/HUJTCHV.png)

Data:
___
![data](https://i.imgur.com/HSdYWjs.png)

**Comment by hypervillain** [comment]
Hey @acd02, so your post-scriptum means that everything is fine on our side? I actually tried and pasted non-breaking spaces in my Rich text editor and could not reproduce your use case either 🤔

**Comment by acd02** [comment]
Yes, problem solved on my side :)

> I actually tried and pasted non-breaking spaces in my Rich text editor and could not reproduce your use case either

weird indeed 🤔
