### ISSUE TITLE
RichText.asText() should not throw error if no content is passed

### ISSUE THREAD

**Issue by jdwillemse** [prismicio/prismic-reactjs#14]
If a field is left blank in Prismic and that field is rendered using `RichText.asText()` and error is thrown
```
TypeError: Cannot read property 'map' of undefined…
```
This requires that every field needs to be checked before being rendered which makes for clumsy code.

If would be great if asText returned and empty string instead.

**Comment by pex** [comment]
As noted in #19 an upgrade of [prismic-richtext](https://github.com/prismicio/prismic-richtext) should solve this issue.
Should be fixed since b16c2553a20cf755182ff25f5a8192c21bef4b03 (actual patch: https://github.com/prismicio/prismic-richtext/commit/dac153b5c3395b46168c272d4e2a474b79998d4d)
