### ISSUE TITLE
Latest npm published version v0.3.1 still includes react@15 as a dependency

### ISSUE THREAD

**Issue by nhardy** [prismicio/prismic-reactjs#15]
The latest npm-published version v0.3.1 still includes react@15 as a dependency. React was converted to a peerDependency in April in 778f50a and changed to allow for `react@>=15.6.1` in August in 2eaff808, but it looks like v0.3.2 needs to be published, so that `prismic-reactjs` can be used with React 16.

**Comment by nhardy** [comment]
@krabbypattified @arnaudlewis Any updates on this?

**Comment by arnaudlewis** [comment]
It's taken care of, you can now pull the new 0.3.2 version ;)
