### ISSUE TITLE
RichText.render doesn't work on IE11 without a polyfill

### ISSUE THREAD

**Issue by erichirlemann** [prismicio/prismic-reactjs#16]
Any use of `RichText.render` does not work under IE11.
`
TypeError: Object doesn't support property or method 'assign'
`

For me, the use of a polyfill as https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill solves the issue.

**Comment by Duaner** [comment]
Thanks @erichirlemann 

Could you do a PR for that if you already have the code in your version of the kit ?

**Comment by erichirlemann** [comment]
I don't have such a version of the kit, in my context I had to put  `Object::assign` polyfill in place for my own code and could solve two problems with it.
