### ISSUE TITLE
fetchLinks Unexpected behaviour JS API

### ISSUE THREAD

**Issue by benpetsch** [prismicio/prismic-reactjs#20]
Unexpected behaviour for the option "fetchLinks".

From the docs I expected that the option is available for all endpoints.

This does not work:
```
    const response = await API.query(
      Prismic.Predicates.at('my.blog_post.uid', slug, {
        fetchLinks: [
          'author.picture',
          'author.test',
          'author.firstname',
          'author.surname',
          'author.short_description'
        ]
      })
    );
```

This does work:
```
    const response = await API.getByUID('blog_post', slug, {
      fetchLinks: [
        'author.picture',
        'author.test',
        'author.firstname',
        'author.surname',
        'author.short_description'
      ]
    });
```

Please add a more explicit definition to the docs of available options for each endpoint.

**Comment by hypervillain** [comment]
Hello @benpetsch, I get your frustration unfortunately this repository does not contain code related to Prismic API! Would you mind opening an issue on https://github.com/prismicio/prismic-javascript?

I'll be closing the issue, don't hesitate to re-open

**Comment by levimykel** [comment]
Hi @benpetsch,

I just wanted to follow up quickly on this. There isn't actually an issue or bug here.

The helper functions like `getByUID` allow you to pass the query options in as third parameter. But when using the standard `query` method, you don't pass the query options in the query Predicates, but as the second parameter of the `query` method. 

Here is how you can pass the query options in this case:
```
const response = await API.query(
  Prismic.Predicates.at('my.blog_post.uid', slug),
  {
    fetchLinks: [
       'author.picture',
        'author.test',
        'author.firstname',
        'author.surname',
        'author.short_description'
      ]
   }
);
```
Give this a try and let me know if it works for you!
