### ISSUE TITLE
Recent update not working in Internet Explorer

### ISSUE THREAD

**Issue by edahlseng** [prismicio/prismic-reactjs#24]
After the recent update to v1.0.0, it appears that this module is failing in Internet Explorer. I'm still not sure why or what the final fix would be. Has anyone else seen this?

**Comment by sambou** [comment]
Yup, same here. The issue seems to be in prismic-richtext, this is what I'm getting on the console:
```
SyntaxError: Expected identifier, string or number at ./node_modules/prismic-richtext/dist/prismic-richtext.min.js
```

**Comment by hypervillain** [comment]
mmh, that's weird. I actually did a PR on prismic-richtext that was supposed to get rid of that kind of issues. See here: https://github.com/prismicio/prismic-richtext/commit/ab1228f89bc714b93c7515ac1072dd18e672e9ae#diff-11e9f7f953edc64ba14b0cc350ae7b9d

I may take some time to investigate next week but any help would be _greatly_ appreciated

**Comment by hypervillain** [comment]
Hey guys,

try updating the package to `1.0.1` and you should be good to go!

**Comment by edahlseng** [comment]
Thanks @hypervillain! We'll give it a shot next week!

**Comment by craigtaub** [comment]
We got same issue on IE11, upgraded to `1.0.1` and now webpack build gets error below (webpack v4).

```
TypeError: Cannot read property 'normalModuleFactory' of undefined

`compiler.hooks.normalModuleFactory.tap(pluginName, nmf => {
^
```

**Comment by hypervillain** [comment]
Perfect, I'll close the issue. Tell me how it goes!

**Comment by craigtaub** [comment]
The update fixed it for us.
