### ISSUE TITLE
Docs for HTML serializer have incorrect import

### ISSUE THREAD

**Issue by davidpmccormick** [prismicio/prismic-reactjs#25]
This docs  at https://prismic.io/docs/reactjs/beyond-the-api/html-serializer have the following:

```
import { RichText } from 'prismic-reactjs';
const Elements = RichText.Elements;
```

I believe this should read:

```
import { RichText, Elements } from 'prismic-reactjs';
```

**Comment by raulg** [comment]
Nice catch! We're currently in the process of updating all of the documentation related to ReactJS to bring it in line with the changes to `prismic-reactjs`. Thanks for letting us know, this will be added to the changes of the reference docs.

**Comment by hypervillain** [comment]
Hey @davidpmccormick,

I believe the documentation is now up to date!
Did you give it a try?

Hugo
