### ISSUE TITLE
Breaks with CSP

### ISSUE THREAD

**Issue by robcalcroft** [prismicio/prismic-reactjs#32]
This might not be your fault but when I'm using Gatsby with your library my CSP complains that it needs `unsafe-eval`:
```
Uncaught (in promise) EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'sha256-6vNRX+9q2xXLVUZlB38JyTMj0RbBVK9hF78wr2cG+qU=' 'sha256-5TUZ2Dus6dN9Z5l9lYGlzJQuP+TNDL7/J7wYBS0C6/A='".

    at Object._ (prismic-reactjs.js:473)
    at t (prismic-reactjs.js:62)
    at ./node_modules/object-assign/index.js (prismic-reactjs.js:256)
    at factory (prismic-reactjs.js:8)
    at Object.237 (prismic-reactjs.js:6)
    at s (bootstrap:89)
    at Module.225 (component---src-components-post-page-index-js-369e6c4c360a51cbbf29.js:1)
    at s (bootstrap:89)
```
Wonder if there is a way round this?

**Comment by hypervillain** [comment]
Hey @robcalcroft,

I _think_ this might come from us injecting embed scripts in the DOM. This is required by the Embed field in Prismic custom types. A quick solution would probably be to whitelist these 3 urls in your CSP meta-tag:

- https://platform.twitter.com
- https://connect.facebook.net
- https://www.instagram.com

I'm open to discussing other solutions of course. If so, it would be awesome if you could provide a small reproduction repository in the meantime!

**Comment by hypervillain** [comment]
Feel free to reopen!
