### ISSUE TITLE
Rich text graphql

### ISSUE THREAD

**Issue by mverissimo** [prismicio/prismic-reactjs#34]
I see that rich-text expect the following props:
`
[{
      type: '',
      text: '',
      spans: [],
}]
`

but the api returns something like that:
`
data {
  description {
    raw {
      type
      text
     }
     html
     text
    }
}
`
I'm using [https://github.com/birkir/gatsby-source-prismic-graphql](url)

**Comment by hypervillain** [comment]
Hey, can you move your issue to [prismic-richtext](https://github.com/prismicio/prismic-richtext)?
