### ISSUE TITLE
Link.url fails for internal links if used with graphql

### ISSUE THREAD

**Issue by ascii-husky** [prismicio/prismic-reactjs#37]
Link component in prismic-helpers used by prismic-reactjs checks for `link_type === "Document"` but graphql returns `_linkType === "Link.document"`. Please see image

![image](https://user-images.githubusercontent.com/8591856/67010720-7bb73e00-f0ee-11e9-8958-29773827c885.png)

Do I use Link.url wrong or is this a bug?

Thanks

**Comment by fchengpc** [comment]
i face the same issue

**Comment by hypervillain** [comment]
Closing in profit of #31
