### ISSUE TITLE
Redundant wrapping div rendered by RichText.render

### ISSUE THREAD

**Issue by jenshedqvist** [prismicio/prismic-reactjs#46]
The `RichText.render` method wraps Prismic StructuredText in a redundant div. This makes for instance using ´React.Children` helpers hard to use on rendered result.

This structured text:
```json
[{"type":"paragraph","text":"With some text:","spans":[{"start":10,"end":19,"type":"strong"}]},{"type":"o-list-item","text":"Info 1","spans":[]},{"type":"o-list-item","text":"Info 2 and link","spans":[{"start":7,"end":15,"type":"hyperlink","data":{"link_type":"Web","url":"https://google.com"}}]},{"type":"o-list-item","text":"Info 3","spans":[]}]
```

Results in:

```html
<div><p>With some <strong>rich text</strong>:</p><ol><li>Info 1</li><li>Info 2 <a href="https://sms.bromma.com/overview">and link</a></li><li>Info 3</li></ol></div>
```

The document says that a *React fragment* is used as a wrapper. Not a `<div>`.

**Comment by Heyrows** [comment]
Hi jenshedqvist,

I couldn't reproduce the issue with the structured text you gave.
Could you reproduce your issue on a code environment like https://codesandbox.io/.
