### ISSUE TITLE
Only standard tag element serializers supported

### ISSUE THREAD

**Issue by dcecile** [prismicio/prismic-reactjs#48]
I tried to override `elements={{[Elements.image]: CustomImage}}`, but got a confusing error:

> `Error: img is a void element tag and must neither have children nor use dangerouslySetInnerHTML.`

This is because for any custom elements, [the library only provides children](https://github.com/prismicio/prismic-reactjs/blob/f5c4c3d/src/richtext.js#L40-L43), which is invalid in the case of `img`.

Maybe in the places where `createElement('...', ...)` is used in `richtext.js`, try checking `elements` first?

**Comment by hypervillain** [comment]
Hey @dcecile ,

it makes a lot of sense. The `elements` property is really new, I'm already happy you tried it out! Expect a fix in the coming days 👍In the meantime, you can use the `htmlSerializer` of course

**Comment by dcecile** [comment]
Thanks, looking forward to it!

I was able to work around this initially using a CSS rule for `img`, but now I want to use [Next.js `Link` components](https://nextjs.org/docs/api-reference/next/link) for hyperlinks within our site.

**Comment by dcecile** [comment]
@hypervillain We'd also like to substitute `button` elements for links to a special content type (deep linking into a chat flow).

I don't see the new code yet, so can you update this issue once the feature is released? We'd start using it right away instead of doing a workaround that would involve HTML building or [element replacing](https://bitsofco.de/anchors-vs-buttons/#whatsthesolution).

**Comment by hypervillain** [comment]
Hey, thanks for your patience, I just merged a PR that should better handle different element types. Thank you for your patience @dcecile

**Comment by dcecile** [comment]
@hypervillain OK thanks, we'll take a look! 👀

**Comment by hypervillain** [comment]
Awesome! It's been deployed as a minor version bump
