### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by alexanderfountain** [prismicio/prismic-reactjs#49]
I'm sourcing prismic via gatsby-source-prismic

I'mm trying to render like this:
{items.map((item, index) => (

      <RichText render={item.content} />

))}

Seems to be from line 588 from prismic-reactjs.js
"var t = e.spans.map(function (t) {"

I have rich text in a repeatable slice. 

Any thoughts would be much appreciated.

**Comment by hypervillain** [comment]
Hey @alexanderfountain ,

sorry you encountered an issue. Can you log `item.content` and paste the result here? It usually means that `prismic-richtext` is passed an empty value, or something that looks like rich text but is not

**Comment by Razinsky** [comment]
I have the same exact problem. In GraphQL my Rich text content type gives
```
{
  html: String
  text: String
  raw: Array<{
    type: String
    text: String
  }>
}
```
If I try to render it with
```
<RichText render={item.content} />
```
I get a simple warning `Rich text argument should be an Array.`

But if I try to render with
```
<RichText render={item.content.raw} />
```
then I get 

![image](https://user-images.githubusercontent.com/3629808/75257212-a018da80-57b2-11ea-87e2-2651546ccb75.png)

Any help would be greatly appreciated.

**Comment by alexanderfountain** [comment]
I was unable to resolve this Razinsky.

My solution was to switch my gatsby-source-prismic from version 2 to version 3.

If you go that route you need to create schema json files containing your content types. You can copy and paste these directly from prismic.

**Comment by hypervillain** [comment]
This might be related to plugin you use, then.
Have you looked at https://github.com/birkir/gatsby-source-prismic-graphql
 instead?

**Comment by alexanderfountain** [comment]
Yes I did. That worked with your richtext, but gatsby-source-prismic-graphql forces you to create pages an odd way via a constrained method in your gatsby-config file instead of the standard more flexible method in your gatsby-node file which I needed.

**Comment by Razinsky** [comment]
Yeah @hypervillain that works but I agree with @alexanderfountain, `gatsby-source-prismic` version 3 works fine. Thanks @alexanderfountain

**Comment by Jezfx** [comment]
Yeah thanks @alexanderfountain — upgrading to v3 was the only way I've been able to get it to work too.
