### ISSUE TITLE
Expose serialisation functions

### ISSUE THREAD

**Issue by haf** [prismicio/prismic-reactjs#50]
If I'm supposed to be able to override singular element type serialisation functions, it would be great to be able to delegate all other types of elements into this code-base. Hence; if you could expose your serialisers, it would be appreciated.

**Comment by hypervillain** [comment]
Hey @haf, can you give me more details of what you mean? Would you like to be able to specify your own serialize functions, like our [`serializeStandardTag`](https://github.com/prismicio/prismic-reactjs/blob/master/src/richtext.js#L48) for example?

**Comment by haf** [comment]
No, I don't, I mean exposing your existing per-type serialisation functions.

**Comment by hypervillain** [comment]
Ok, we can definitely do that. How would you make use of them?

**Comment by haf** [comment]
I ended up copying your code instead; but what I would have done would have been to delegate to them from my own clone of your main serialise function, as to keep the behaviour the same for everything except the single serialisation function I wished to override. 

The use case was rendering NextJS links.

**Comment by hypervillain** [comment]
Ok, it definitely makes sense!

Have you tried using the `elements` property?

```javascript
<RichText render={myField} elements={{ hyperlink: () => <NextLink /> }}
````

**Comment by haf** [comment]
I think I tried it, but it’s been too long and I don’t remember why I didn’t use it. Sorry

**Comment by hypervillain** [comment]
haha no problem, we added the prop not so long ago, it may even not have been available at the time! Thanks for your contribution ✌️
