### ISSUE TITLE
Prop type validation is wrong for RichText Component prop

### ISSUE THREAD

**Issue by Razinsky** [prismicio/prismic-reactjs#54]
Currently the prop type of the `Component` prop of the `RichText` component is `node` which is wrong and trigger a warning when choosing a valid React component. The code works, just the validation is wrong. The right prop type should be `elementType` instead.

A PR is ready if someone could grant me access.

**Comment by hypervillain** [comment]
Hey @Razinsky, definitely.
I'm releasing small changes so I'll add this on top of them.

For other times: I can't grant you access (not being an admin myself) but usually you can create a pull request from a fork of this repo
