### ISSUE TITLE
asText doesn't add newlines where it should

### ISSUE THREAD

**Issue by aequasi** [prismicio/prismic-reactjs#56]
https://user-guides.prismic.io/en/articles/3690367-writing-markdown-in-a-prismic-field

Following this, trying to parse a markdown doc, and I'm having some trouble with it. It seems as though `asText` doesn't put newlines between separate paragraphs, divs, headers, etc. This makes it impossible to parse markdown'ed content with multiple paragraphs.

**Comment by hypervillain** [comment]
This is a bit out of the scope of `prismic-reactjs` as the text field is solely handled by the API. One way to solve this is to rely on the paragraphs array instead and parse each separately
