### ISSUE TITLE
asText(undefined) TypeError

### ISSUE THREAD

**Issue by ohlr** [prismicio/prismic-reactjs#57]
`RichText.asText(undefined)` results in the following runtime error in development mode.
On building the page it causes to fail the build.

Is this intended?

```
TypeError: Cannot read property 'map' of undefined
r [as asText]
node_modules/prismic-reactjs/dist/prismic-reactjs.js:871
  868 | 
  869 | var r = function (e, t) {
  870 |   var n = "string" == typeof t ? t : " ";
> 871 |   return e.map(function (e) {
  872 |     return e.text;
  873 |   }).join(n);
  874 | };
```

**Comment by hypervillain** [comment]
Hey @ohlr, I wouldn't say intended as it's simply passed to RichText, I believe. I'll talk with the dev team if it's something we could change on `prismic-dom`. In any case, we can add a check in the React package. Would you mind opening a PR?

**Comment by ohlr** [comment]
so @hypervillain  whats the status?

**Comment by ohlr** [comment]
@hypervillain when do you plan the next release?
