### ISSUE TITLE
Publish version `1.3.3`

### ISSUE THREAD

**Issue by Levino** [prismicio/prismic-reactjs#73]
You updated the package version to `1.3.3` but npm only knows version `1.3.2`. How is that?
https://github.com/prismicio/prismic-reactjs/blob/c6353ea465ae0575da4e3559465767d9def76f77/package.json#L3

**Comment by Levino** [comment]
Ah, the build [failed](https://github.com/prismicio/prismic-reactjs/runs/1071022659)...
> npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/prismic-reactjs - You do not have permission to publish "prismic-reactjs". Are you logged in as the correct user?

I recommend not publishing via CD tools. That is also why there is #72.

**Comment by YoannDelpierre** [comment]
@MarcMcIntosh any idea if you have time to fix 1.3.3 build ?

Thanks

**Comment by hypervillain** [comment]
@Levino it's an issue with our organisation on NPM not having rights on the package... We will have to move it @prismicio/react in the next version. Note that the GH action only publishes alpha versions of prismic-reactjs, so technically we still push manually

**Comment by lihbr** [comment]
I'm not sure where this was at, `prismic-reactjs@1.3.3` was published so closing this issue, feel free to reopen if anything!
