### ISSUE TITLE
Serialize string (`"Hello <span>World</span>"`) to jsx 

### ISSUE THREAD

**Issue by JohanMouchet** [prismicio/prismic-reactjs#75]
I'm defining a _Custom Type_ with a _Rich Text_ field,
I'm creating a _Document_ with this _Custom Type_ and filling the _Rich Text_ field with `Hello <span>World</span>` (as a string).

When passing the data to the `<RichText />`, simplified like so
```
<RichText
  render={{
    type: ...,
    text: "Hello <span>World</span>",
    spans: ...,
  }}
/>
```

The output is an html element `<p>Hello <span>World</span></p>` where `<p>` is an html Element, but `<span>` is a string:
![image](https://user-images.githubusercontent.com/16338730/94243591-f1609680-ff5a-11ea-97c9-e6fc0a6a34f9.png)

I suspect the string isn't serialized to avoid XSS attacks.

I've been trying to use `htmlSerializer` in combination with [DOMPurify](https://github.com/cure53/DOMPurify), without success.

Can this be achieved, is there an alternative?

**Comment by hypervillain** [comment]
Hey @JohanMouchet, RichText is not meant to be used this way. If you really need this to work, you can use `dangerouslySetInnerHTML`. You will have to purify it yourself though, but won't be able to rely on our RichText component

**Comment by JohanMouchet** [comment]
Hi @hypervillain,

I thought so, thank you for the confirmation.

For anyone facing the same issue, I worked around it by using a _Preformatted_ field which I passed to [DOMPurify ](https://github.com/cure53/DOMPurify) (to prevent from XSS attacks) and then [HTMLReactParser](https://github.com/remarkablemark/html-react-parser#readme) (to convert the string to markup).

I'm closing this issue,
Keep up the great work on the repo 👍
