### ISSUE TITLE
Customize RichText.render output without re-implementing an HTML serializer

### ISSUE THREAD

**Issue by sarahdayan** [prismicio/prismic-reactjs#78]
Hi Prismic team, and thanks for the SDK 🙂

This is not a bug report, more of a feature request.

I'm using `RichText.render` to render rich text content from Prismic as HTML, and I need to access my paragraphs (`<p>` tags) so that I can add class names to them. From what I've understood of the documentation, the way to do so is to [implement an HTML serializer](https://prismic.io/docs/technologies/html-serializer-reactjs#adding-the-html-serializer-functions) myself and pass it to `RichText` (used as a React component).

The issue is that to change the output of a single element, I need to re-implement an entire serializer. Sure I could copy the code from the Prismic sources (or the [example from the docs](https://prismic.io/docs/technologies/html-serializer-reactjs#example-with-all-elements)), but if I do, I won't benefit from bug fixes or improvements of the default HTML serializer from this SDK.

Could we imagine a callback as a second parameter of `RichText.render` (_à la_ `serializeHyperlink`) to run user code in the serializer? Something like:

```js
RichText.render(html, (type, element, content, children, index) => {
  if (type === Elements.paragraph) {
    return React.createElement('p', { className: 'paragraph-class' }, children);
  }
});
```

The callback would run in the [serialize](https://github.com/prismicio/prismic-reactjs/blob/master/src/richtext.js#L7) function, allowing users to hook into it.

Another approach, to avoid growing the surface API, could be to expose the default HTML serializer (it's currently private). This way, users can implement their own serializer by wrapping Prismic one, so all they have to do is add their custom code. For example:

```jsx
// other imports
import { htmlSerializer } from 'prismic-reactjs';

function customHtmlSerializer(type, element, content, children, key) {
  if (type === Elements.paragraph) {
    return React.createElement('p', { className: 'paragraph-class' }, children);
  }

  htmlSerializer(type, element, content, children, key);
}

<RichText render={html} htmlSerializer={customHtmlSerializer} />;
```

Does it make sense?

I'd be happy to PR if any of these options sound interesting to you.

**Comment by lihbr** [comment]
Hi @sarahdayan, thanks for the comprehensive issue!

If I got it correctly, you want to serialize a rich text field, keeping the default behavior for all tags, except for paragraphs to which you want to add an additional class to. If that's correct you can create a really simple htmlSerializer like so, similar to what you were suggesting actually:
```javascript
function htmlSerializer(type, element, content, children, key) {
  if (type === Elements.paragraph) {
    return React.createElement('p', { className: 'paragraph-class' }, children);
  }

  return null; // Returning null makes the serializer fallback to its default behavior
}
```
The secret resides in the `return null;` statement, which basically hides the `htmlSerializer(...)` suggested in your second approach 🙂

Let me know if that helps! I'll let know our documentation team that perhaps the HTML Serializer page isn't clear enough on that one~

**Comment by sarahdayan** [comment]
Hey @lihbr, thanks for the prompt reply! I just realized that this is what the following piece of docs meant 🤦🏻‍♀️

>Make sure to add a default case that returns null. This will leave all the other elements untouched.

Thanks a lot, closing the issue now 🙂
