### ISSUE TITLE
Unable to handle multiple stylings

### ISSUE THREAD

**Issue by levimykel** [prismicio/prismic-reactjs#9]
The kit currently is unable to handle multiple stylings of the same text in a Rich Text field. 

For example, if you put everything in bold, and one part of the text in italic on top of the already bold, it renders only the strong tag, the em tag is missing.

Along with this if you put text in bold, and I set a link on 2 different words on top of the bold, only the last link will be rendered to an anchor tag.

**Comment by hypervillain** [comment]
Hey @levimykel , this one has probably been solved in prismic-richtext ✌️
